version: '3.8'
services:
  dev-db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmarks
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data